"""Print Firebase env vars formatted for paste-into-Vercel.

Reads serviceAccount.json (downloaded from the Firebase console), validates
it, and prints the four env vars Vercel needs:

  APP_STORAGE_MODE
  FIREBASE_PROJECT_ID
  SECRET_KEY
  FIREBASE_CREDENTIALS_JSON

Usage:
    python scripts/prepare_vercel_env.py
    python scripts/prepare_vercel_env.py --file serviceAccount.json
    python scripts/prepare_vercel_env.py --auth firebase   # also prints AUTH_PROVIDER
    python scripts/prepare_vercel_env.py --one-line        # compact JSON
    python scripts/prepare_vercel_env.py --dotenv .env.vercel  # write a .env-style file
"""
import argparse
import json
import os
import secrets
import string
import sys
from pathlib import Path


REQUIRED_KEYS = {
    "type", "project_id", "private_key_id", "private_key",
    "client_email", "client_id",
}


def generate_secret(length=64):
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*-_=+"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--file", default="serviceAccount.json",
                        help="Path to the Firebase service-account JSON file (default: serviceAccount.json)")
    parser.add_argument("--auth", choices=["firebase", "local"], default="firebase",
                        help="Value for AUTH_PROVIDER (default: firebase)")
    parser.add_argument("--one-line", action="store_true",
                        help="Print FIREBASE_CREDENTIALS_JSON as a single compact line")
    parser.add_argument("--dotenv",
                        help="Also write the env vars to this .env-style file (e.g. .env.vercel)")
    parser.add_argument("--secret-key", default=None,
                        help="Use this SECRET_KEY instead of generating a fresh one")
    args = parser.parse_args()

    path = Path(args.file)
    if not path.exists():
        sys.exit(
            f"\nFile not found: {path}\n\n"
            "How to get serviceAccount.json:\n"
            "  1. Open  https://console.firebase.google.com/project/kg-ticket/settings/serviceaccounts/adminsdk\n"
            "  2. Click 'Generate new private key' (downloads a JSON file)\n"
            "  3. Save it as 'serviceAccount.json' here (or pass --file <path>)\n"
            "  4. Re-run this script.\n"
        )

    raw = path.read_text(encoding="utf-8")
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        sys.exit(f"\n{path} is not valid JSON: {e}")

    missing = REQUIRED_KEYS - set(data.keys())
    if missing:
        sys.exit(f"\n{path} is not a Firebase service account. Missing keys: {sorted(missing)}")

    project_id   = data.get("project_id", "")
    client_email = data.get("client_email", "")
    secret_key   = args.secret_key or generate_secret()
    cred_value   = json.dumps(data, separators=(",", ":")) if args.one_line else json.dumps(data, indent=2)

    api_key = os.environ.get("FIREBASE_API_KEY", "")

    env_vars = [
        ("APP_NAME",                "KG Ticket Control"),
        ("SECRET_KEY",              secret_key),
        ("APP_STORAGE_MODE",        "firebase"),
        ("AUTH_PROVIDER",           args.auth),
        ("FIREBASE_PROJECT_ID",     project_id),
        *([("FIREBASE_API_KEY",     api_key)] if api_key else []),
        ("FIREBASE_CREDENTIALS_JSON", cred_value),
    ]

    print()
    print("=" * 76)
    print("  Vercel Environment Variables")
    print("  Paste each Name/Value pair under Settings → Environment Variables")
    print(f"  Service account: {client_email}")
    print("=" * 76)

    for name, value in env_vars:
        print()
        print(f"  Name:  {name}")
        if "\n" in value:
            print(f"  Value (multi-line, paste verbatim):")
            for line in value.splitlines():
                print(f"    {line}")
        else:
            print(f"  Value: {value}")

    print()
    print("=" * 76)
    print("  After saving all variables, redeploy from Vercel → Deployments")
    print("=" * 76)

    if args.dotenv:
        out = Path(args.dotenv)
        with out.open("w", encoding="utf-8") as f:
            f.write("# Generated by scripts/prepare_vercel_env.py\n")
            f.write("# Paste these as Environment Variables in Vercel.\n\n")
            for name, value in env_vars:
                if "\n" in value:
                    # quote multi-line value as a single literal
                    f.write(f"{name}='{value}'\n")
                else:
                    f.write(f"{name}={value}\n")
        print(f"\n  Wrote: {out.resolve()}")


if __name__ == "__main__":
    main()
