export const ROLES = {
  REQUEST_USER: "Request User",
  AUTHORIZED_PERSON: "Authorized Person",
  TEAM_LEAD: "Management / Team Lead",
  WORK_MEMBER: "Work Team Member",
  ADMIN: "Admin",
  SUPER_ADMIN: "Super Admin",
};

// User-friendly status labels shown in the UI
export const STATUS_LABELS = {
  "Pending Authorization": "Waiting for Approval",
  "Need More Information": "Need Your Reply",
  "Approved": "Approved",
  "Assigned to Team": "Assigned to Team",
  "In Progress": "Work in Progress",
  "On Hold": "On Hold",
  "Completed": "Work Done",
  "Verified": "Checked",
  "Closed": "Closed",
  "Reopened": "Reopened",
  "Rejected": "Rejected",
  "Draft": "Draft",
  "Submitted": "Submitted",
  "Work Updated": "Work Updated",
  "Cancelled": "Cancelled",
  "Duplicate": "Duplicate",
};

// Urgency options shown to normal users → maps to internal priority
export const URGENCY_OPTIONS = [
  { label: "Work stopped",           sub: "Cannot work at all",    priority: "Urgent" },
  { label: "Need today",             sub: "Important, need today",  priority: "High" },
  { label: "Normal issue",           sub: "Can wait a day or two",  priority: "Medium" },
  { label: "Small change",           sub: "Low impact request",     priority: "Low" },
];

export const NOTE_TYPES = [
  "User Comment",
  "Approval Note",
  "Work Note",
  "Internal Note",
  "Resolution Note",
  "Reopen Note",
];

export const VISIBILITY = {
  PUBLIC: "Public",
  INTERNAL: "Internal",
};

export const SYSTEMS = ["Lattice", "Trybe"];

export const AREA_OPTIONS = {
  Lattice: ["Pricing", "Report", "Mapping", "Payroll", "Access"],
  Trybe: ["Labour", "Mapping", "Report", "Transaction", "Reconciliation"],
};

export const CATEGORY_OPTIONS = [
  "Bug",
  "New Requirement",
  "Data Issue",
  "Change Request",
];

export const PRIORITY_OPTIONS = ["Urgent", "High", "Medium", "Low"];

export const STATUS_ORDER = [
  "Draft",
  "Submitted",
  "Pending Authorization",
  "Approved",
  "Assigned to Team",
  "In Progress",
  "Work Updated",
  "Completed",
  "Verified",
  "Closed",
  "Rejected",
  "Need More Information",
  "On Hold",
  "Reopened",
  "Cancelled",
  "Duplicate",
];

export const DEMO_USERS = [
  {
    id: "user-request-aisha",
    name: "Aisha Khan",
    role: ROLES.REQUEST_USER,
    area: "Pricing",
    system: "Lattice",
  },
  {
    id: "user-request-ravi",
    name: "Ravi Nair",
    role: ROLES.REQUEST_USER,
    area: "Labour",
    system: "Trybe",
  },
  {
    id: "user-auth-lattice",
    name: "Meera Joseph",
    role: ROLES.AUTHORIZED_PERSON,
    area: "Pricing",
    system: "Lattice",
  },
  {
    id: "user-auth-trybe",
    name: "Arjun Patel",
    role: ROLES.AUTHORIZED_PERSON,
    area: "Mapping",
    system: "Trybe",
  },
  {
    id: "user-lead-platform",
    name: "Farah Siddiqui",
    role: ROLES.TEAM_LEAD,
    teamId: "team-platform",
  },
  {
    id: "user-lead-data",
    name: "Karan Babu",
    role: ROLES.TEAM_LEAD,
    teamId: "team-data",
  },
  {
    id: "user-work-imran",
    name: "Imran Shaikh",
    role: ROLES.WORK_MEMBER,
    teamId: "team-platform",
  },
  {
    id: "user-work-nila",
    name: "Nila Das",
    role: ROLES.WORK_MEMBER,
    teamId: "team-data",
  },
  {
    id: "user-admin",
    name: "Admin Desk",
    role: ROLES.ADMIN,
  },
  {
    id: "user-super-admin",
    name: "Super Admin",
    role: ROLES.SUPER_ADMIN,
  },
];

export const DEMO_TEAMS = [
  {
    id: "team-platform",
    teamName: "Platform Delivery",
    system: "Lattice",
    teamLeadId: "user-lead-platform",
    memberIds: ["user-work-imran"],
    isActive: true,
  },
  {
    id: "team-data",
    teamName: "Data Integrity Squad",
    system: "Trybe",
    teamLeadId: "user-lead-data",
    memberIds: ["user-work-nila"],
    isActive: true,
  },
];

export const AUTHORIZER_BY_SYSTEM_AREA = [
  { system: "Lattice", area: "Pricing", authorizerId: "user-auth-lattice" },
  { system: "Lattice", area: "Report", authorizerId: "user-auth-lattice" },
  { system: "Lattice", area: "Mapping", authorizerId: "user-auth-lattice" },
  { system: "Trybe", area: "Labour", authorizerId: "user-auth-trybe" },
  { system: "Trybe", area: "Mapping", authorizerId: "user-auth-trybe" },
  { system: "Trybe", area: "Report", authorizerId: "user-auth-trybe" },
  { system: "Trybe", area: "Transaction", authorizerId: "user-auth-trybe" },
  { system: "Trybe", area: "Reconciliation", authorizerId: "user-auth-trybe" },
];

function hoursAgo(hours) {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

export function createSeedState() {
  const tickets = [
    {
      id: "ticket-101",
      ticketNo: "TKT-101",
      system: "Trybe",
      area: "Mapping",
      category: "Data Issue",
      priority: "Urgent",
      title: "Trybe employee mapping mismatch on labour upload",
      description:
        "Rows are appearing in Trybe transaction export but missing from Labour employee mapping. Need validation and corrected mapping outcome.",
      status: "Pending Authorization",
      createdBy: "user-request-ravi",
      authorizedPersonId: "user-auth-trybe",
      approvedBy: "",
      approvedAt: "",
      rejectedBy: "",
      rejectedAt: "",
      rejectionReason: "",
      assignedTeamId: "",
      assignedTo: "",
      dueDate: "",
      expectedDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      completedBy: "",
      completedAt: "",
      closedBy: "",
      closedAt: "",
      reopenCount: 0,
      attachmentNames: ["trybe-mapping-gap.xlsx"],
      label: "TRYBE-MAP",
      reporter: "Ravi Nair",
      verifier: "Arjun Patel",
      workBatch: "TRB-MAP-05",
      workspaceName: "Trybe Payroll",
      resolutionNote: "",
      rootCause: "",
      createdAt: hoursAgo(5),
      updatedAt: hoursAgo(5),
    },
    {
      id: "ticket-102",
      ticketNo: "TKT-102",
      system: "Lattice",
      area: "Pricing",
      category: "Bug",
      priority: "High",
      title: "Pricing total shows incorrect final amount for batch close",
      description:
        "Lattice finalization is adding stale pricing rows after a recalculation. Final total in the report no longer matches exported totals.",
      status: "In Progress",
      createdBy: "user-request-aisha",
      authorizedPersonId: "user-auth-lattice",
      approvedBy: "user-auth-lattice",
      approvedAt: hoursAgo(30),
      rejectedBy: "",
      rejectedAt: "",
      rejectionReason: "",
      assignedTeamId: "team-platform",
      assignedTo: "user-work-imran",
      dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      expectedDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
      completedBy: "",
      completedAt: "",
      closedBy: "",
      closedAt: "",
      reopenCount: 0,
      attachmentNames: ["pricing-proof.png", "recalc-output.csv"],
      label: "LAT-PRICE",
      reporter: "Aisha Khan",
      verifier: "Meera Joseph",
      workBatch: "LAT-PRI-18",
      workspaceName: "Lattice Core",
      resolutionNote: "",
      rootCause: "",
      createdAt: hoursAgo(34),
      updatedAt: hoursAgo(2),
    },
    {
      id: "ticket-103",
      ticketNo: "TKT-103",
      system: "Trybe",
      area: "Labour",
      category: "Change Request",
      priority: "Medium",
      title: "Need summary note on labour exception dashboard",
      description:
        "Add a summary note block to the exception dashboard so reconciliation teams can see why transactions failed in one place.",
      status: "Need More Information",
      createdBy: "user-request-ravi",
      authorizedPersonId: "user-auth-trybe",
      approvedBy: "",
      approvedAt: "",
      rejectedBy: "",
      rejectedAt: "",
      rejectionReason: "",
      assignedTeamId: "",
      assignedTo: "",
      dueDate: "",
      expectedDate: "",
      completedBy: "",
      completedAt: "",
      closedBy: "",
      closedAt: "",
      reopenCount: 0,
      attachmentNames: [],
      label: "TRYBE-LAB",
      reporter: "Ravi Nair",
      verifier: "Arjun Patel",
      workBatch: "TRB-LAB-02",
      workspaceName: "Trybe Labour",
      resolutionNote: "",
      rootCause: "",
      createdAt: hoursAgo(20),
      updatedAt: hoursAgo(8),
    },
    {
      id: "ticket-104",
      ticketNo: "TKT-104",
      system: "Lattice",
      area: "Report",
      category: "Data Issue",
      priority: "High",
      title: "Report export missing verifier column for completed work batch",
      description:
        "Completed work batches should display verifier info in export. Current report omits verifier data even when closure is done.",
      status: "Completed",
      createdBy: "user-request-aisha",
      authorizedPersonId: "user-auth-lattice",
      approvedBy: "user-auth-lattice",
      approvedAt: hoursAgo(80),
      rejectedBy: "",
      rejectedAt: "",
      rejectionReason: "",
      assignedTeamId: "team-platform",
      assignedTo: "user-work-imran",
      dueDate: hoursAgo(-24).slice(0, 10),
      expectedDate: "",
      completedBy: "user-work-imran",
      completedAt: hoursAgo(4),
      closedBy: "",
      closedAt: "",
      reopenCount: 0,
      attachmentNames: ["verifier-export-before-after.pdf"],
      label: "LAT-REP",
      reporter: "Aisha Khan",
      verifier: "Meera Joseph",
      workBatch: "LAT-REP-03",
      workspaceName: "Lattice Reporting",
      resolutionNote: "Verifier column restored in export projection and QA proof attached.",
      rootCause: "Projection mapper was not updated after the export schema changed.",
      createdAt: hoursAgo(96),
      updatedAt: hoursAgo(4),
    },
  ];

  const notes = [
    {
      id: "note-201",
      ticketId: "ticket-101",
      noteType: "User Comment",
      noteText:
        "Mismatch found in Trybe file, not found in Labour employee mapping. Need the team to validate both directions.",
      visibility: VISIBILITY.PUBLIC,
      createdBy: "user-request-ravi",
      createdAt: hoursAgo(5),
    },
    {
      id: "note-202",
      ticketId: "ticket-102",
      noteType: "Approval Note",
      noteText: "Approved as production-impacting pricing defect. Route to Platform Delivery.",
      visibility: VISIBILITY.INTERNAL,
      createdBy: "user-auth-lattice",
      createdAt: hoursAgo(30),
    },
    {
      id: "note-203",
      ticketId: "ticket-102",
      noteType: "Work Note",
      noteText:
        "Checked Lattice pricing calculation issue. Problem found in finalization logic. Fix staged for testing.",
      visibility: VISIBILITY.PUBLIC,
      createdBy: "user-work-imran",
      createdAt: hoursAgo(2),
    },
    {
      id: "note-204",
      ticketId: "ticket-103",
      noteType: "Approval Note",
      noteText: "Need exact screenshot of the current labour exception widget and target copy.",
      visibility: VISIBILITY.PUBLIC,
      createdBy: "user-auth-trybe",
      createdAt: hoursAgo(8),
    },
    {
      id: "note-205",
      ticketId: "ticket-104",
      noteType: "Resolution Note",
      noteText:
        "Verifier column restored in the report export. Added regression coverage in export mapping test set.",
      visibility: VISIBILITY.PUBLIC,
      createdBy: "user-work-imran",
      createdAt: hoursAgo(4),
    },
  ];

  const approvalHistory = [
    {
      id: "approval-301",
      ticketId: "ticket-102",
      action: "Approved",
      actionBy: "user-auth-lattice",
      actionAt: hoursAgo(30),
      note: "Urgent pricing issue moved to Platform Delivery.",
    },
    {
      id: "approval-302",
      ticketId: "ticket-103",
      action: "Need More Information",
      actionBy: "user-auth-trybe",
      actionAt: hoursAgo(8),
      note: "Please attach example of desired summary note.",
    },
    {
      id: "approval-303",
      ticketId: "ticket-104",
      action: "Approved",
      actionBy: "user-auth-lattice",
      actionAt: hoursAgo(80),
      note: "Report export issue approved for work.",
    },
  ];

  const statusHistory = [
    {
      id: "history-401",
      ticketId: "ticket-101",
      oldStatus: "Submitted",
      newStatus: "Pending Authorization",
      changedBy: "user-request-ravi",
      changedAt: hoursAgo(5),
      note: "Ticket submitted to authorized person.",
    },
    {
      id: "history-402",
      ticketId: "ticket-102",
      oldStatus: "Pending Authorization",
      newStatus: "Approved",
      changedBy: "user-auth-lattice",
      changedAt: hoursAgo(30),
      note: "Ticket approved for Platform Delivery.",
    },
    {
      id: "history-403",
      ticketId: "ticket-102",
      oldStatus: "Approved",
      newStatus: "Assigned to Team",
      changedBy: "user-lead-platform",
      changedAt: hoursAgo(28),
      note: "Assigned to Imran Shaikh.",
    },
    {
      id: "history-404",
      ticketId: "ticket-102",
      oldStatus: "Assigned to Team",
      newStatus: "In Progress",
      changedBy: "user-work-imran",
      changedAt: hoursAgo(24),
      note: "Work started.",
    },
    {
      id: "history-405",
      ticketId: "ticket-103",
      oldStatus: "Pending Authorization",
      newStatus: "Need More Information",
      changedBy: "user-auth-trybe",
      changedAt: hoursAgo(8),
      note: "Awaiting screenshot and target content.",
    },
    {
      id: "history-406",
      ticketId: "ticket-104",
      oldStatus: "In Progress",
      newStatus: "Completed",
      changedBy: "user-work-imran",
      changedAt: hoursAgo(4),
      note: "Fix complete and proof attached.",
    },
  ];

  const notifications = [
    {
      id: "notify-501",
      title: "New ticket needs approval",
      message: "TKT-101 sent to Trybe authorized person for review.",
      type: "TICKET_APPROVAL",
      ticketNo: "TKT-101",
      recordId: "ticket-101",
      receiverId: "user-auth-trybe",
      isRead: false,
      createdAt: hoursAgo(5),
      createdBy: "user-request-ravi",
    },
    {
      id: "notify-502",
      title: "Ticket approved",
      message: "TKT-102 approved and routed to Platform Delivery.",
      type: "TICKET_APPROVED",
      ticketNo: "TKT-102",
      recordId: "ticket-102",
      receiverId: "user-lead-platform",
      isRead: false,
      createdAt: hoursAgo(30),
      createdBy: "user-auth-lattice",
    },
    {
      id: "notify-503",
      title: "Work done — needs your closure",
      message: "TKT-104 completed and waiting for verification.",
      type: "TICKET_DONE",
      ticketNo: "TKT-104",
      recordId: "ticket-104",
      receiverId: "user-auth-lattice",
      isRead: false,
      createdAt: hoursAgo(4),
      createdBy: "user-work-imran",
    },
    {
      id: "notify-504",
      title: "New ticket needs approval",
      message: "TKT-101 is waiting for your review.",
      type: "TICKET_APPROVAL",
      ticketNo: "TKT-101",
      recordId: "ticket-101",
      receiverId: "user-admin",
      isRead: false,
      createdAt: hoursAgo(5),
      createdBy: "system",
    },
  ];

  return {
    users: DEMO_USERS,
    teams: DEMO_TEAMS,
    tickets,
    notes,
    approvalHistory,
    statusHistory,
    notifications,
    meta: {
      currentUserId: "user-auth-lattice",
      lastTicketNumber: 104,
      lastSavedAt: new Date().toISOString(),
    },
  };
}
